### ISSUE TITLE
Problem with method "getToken"

### ISSUE THREAD

**Issue by aminespinoza** [hailiang-wang/DirectLineApi#6]
When I try to create a token by using method getToken like this:

var botclient = require('directline-api');
var secret = 'mi secret key';
var token = client.getToken(secret);

botclient.createConversation(token);

I get the following:
/home/taller/Documentos/ClonedRepos/BotFalabellaJs/testingscripts/botdirect.js:3
var token = botclient.getToken(secret);
                      ^

TypeError: botclient.getToken is not a function
    at Object.<anonymous> (/home/taller/Documentos/ClonedRepos/BotFalabellaJs/testingscripts/botdirect.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

Am I creating something wrong or is really an issue?

**Comment by aminespinoza** [comment]
As a matter of fact, I got the same problem in the test file:

> directline-api@1.1.2 test /home/taller/Documentos/ClonedRepos/BotFalabellaJs/node_modules/directline-api
> ava


   1 failed


   1. DirectLineAPI#dialog
   failed with "directLineAPI.getToken is not a function"
      Test.fn (test.js:173:19)
    Array.map (<anonymous>)
    process._tickCallback (internal/process/next_tick.js:178:19)
npm ERR! Test failed.  See above for more details.

**Comment by Samurais** [comment]
Looks wired. 
What version of nodejs are you using?
